Account:
  type: object
  config:
    description: "Account details"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the account."
      full_name:
        type: "String"
        description: "Full name of the user"
      date_of_birth:
        type: "DateTime"
        description: "Date of birth user"
      gender:
        type: "String"
        description: "Sex of the user"
      email:
        type: "String"
        description: "email of the user"
      phone_number:
        type: "String"
        description: "Phone number of the user"
      street_address_line1:
        type: "String"
        description: "Address of the user"
      street_address_line2:
        type: "String"
        description: "Address of the user"
      city:
        type: "String"
        description: "City of the user"
      post_code:
        type: "String"
        description: "Post code of the user Apartment"
      disabilities:
        type: "String"
        description: "Disabilities"