Config:
  type: object
  config:
    description: "System configuration key-value pair"
    fields:
      code:
        type: "String"
        description: "Unique configuration key (e.g., 'maintenance-mode')"
      value:
        type: "String"
        description: "Configuration value in string format"