Footer:
  type: object
  config:
    description: "Website footer navigation item"
    fields:
      id:
        type: "Int"
        description: "Unique footer item identifier"
      column_footer:
        type: "Int"
        description: "Column number (1-4 typically)"
      title:
        type: "String"
        description: "Display text for the link"
      value:
        type: "String"
        description: "URL or route destination"
      position:
        type: "String"
        description: "Vertical ordering (top/middle/bottom)"
      type:
        type: "Int"
        description: "Item type (1=link, 2=header, 3=divider)"