Menu:
  type: object
  config:
    description: "Website navigation menu item"
    fields:
      id:
        type: "Int"
        description: "Unique menu item identifier"
      parent_id:
        type: "Int"
        description: "Parent item ID for hierarchical menus"
      title:
        type: "String"
        description: "Display text for the menu item"
      url:
        type: "String"
        description: "Destination URL or route"