Mutation:
  type: object
  config:
    fields:
      CreateAccount:
        type: User!
        resolve: "@=mutation('create_account', args['input'])"
        args:
          input:
            type: CreateAccountInput!
      LoginAccount:
        type: Token!
        resolve: "@=mutation('login_account', args['input'])"
        args:
          input:
            type: LoginAccountInput!
      CreateContactForm:
        type: ContactForm!
        resolve: "@=mutation('create_contact_form', args['input'])"
        args:
          input:
            type: CreateContactFormInput!
      CreateChat:
        type: Chat!
        resolve: "@=mutation('create_chat', args['input'])"
        args:
          input:
            type: CreateChatInput!
      SendMessage:
        type: Message!
        resolve: "@=mutation('send_message', args['input'])"
        args:
          input:
            type: SendMessageInput!

CreateAccountInput:
  type: input-object
  config:
    fields:
      email:
        type: "String!"
      username:
        type: "String"
      password:
        type: "String!"
      fullName:
        type: "String"
      dateOfBirth:
        type: "DateTime"
      gender:
        type: "String"
      phoneNumber:
        type: "String"
      streetAddressLine1:
        type: "String"
      streetAddressLine2:
        type: "String"
      city:
        type: "String"
      postCode:
        type: "String"
      disabilities:
        type: "String"

LoginAccountInput:
  type: input-object
  config:
    fields:
      email:
        type: "String!"
      password:
        type: "String!"

CreateContactFormInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
      email:
        type: "String!"
      subject:
        type: "String!"
      message:
        type: "String!"

CreateChatInput:
  type: input-object
  config:
    fields:
      userId:
        type: "Int!"
      adminId:
        type: "Int!"

SendMessageInput:
  type: input-object
  config:
    fields:
      chatId:
        type: "Int!"
      senderId:
        type: "Int!"
      content:
        type: "String!"