services:
  php:
    container_name: "${PHP_CONTAINER_NAME}"
    build:
      context: ./php
      args:
        XDEBUG_CLIENT_HOST: "${XDEBUG_CLIENT_HOST}"
        XDEBUG_CLIENT_PORT: "${XDEBUG_CLIENT_PORT}"
        XDEBUG_IDE_KEY: "${XDEBUG_IDE_KEY}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "${APP_VOLUME}"
    depends_on:
      - database

  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${APP_VOLUME}"
      - "${NGINX_CONF_VOLUME}"
    depends_on:
      - php
      - database

  database:
    container_name: "${DATABASE_CONTAINER_NAME}"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "${MYSQL_VOLUME}"
  elasticsearch:
    container_name: "${ELASTICSEARCH_CONTAINER_NAME:-elasticsearch}"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  es_data:
    driver: local