services:
  php:
    container_name: "${PHP_CONTAINER_NAME}"
    build:
      context: ./php
      args:
        XDEBUG_CLIENT_HOST: "${XDEBUG_CLIENT_HOST}"
        XDEBUG_CLIENT_PORT: "${XDEBUG_CLIENT_PORT}"
        XDEBUG_IDE_KEY: "${XDEBUG_IDE_KEY}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "${APP_VOLUME}"
    depends_on:
      - database

  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${APP_VOLUME}"
      - "${NGINX_CONF_VOLUME}"
    depends_on:
      - php
      - database

  database:
    container_name: "${DATABASE_CONTAINER_NAME}"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "${MYSQL_VOLUME}"