version: '3.0'

services:
  php:
    container_name: redepy_php
    build:
      context: ./php
      args:
        XDEBUG_CLIENT_HOST: "${XDEBUG_CLIENT_HOST:-172.17.0.1}"
        XDEBUG_CLIENT_PORT: "${XDEBUG_CLIENT_PORT:-9001}"
        XDEBUG_IDE_KEY: "${XDEBUG_IDE_KEY:-PHPSTORM}"
    extra_hosts:
      - '172.17.0.1:host-gateway'
    volumes:
      - ./app:/var/www/de-headless-symfony
    depends_on:
      - database
  nginx:
    container_name: redepy_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/de-headless-symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  database:
    container_name: redepy_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: de-headless-symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
