parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Doctrine\ORM\EntityManager: "@doctrine.orm.default_entity_manager"
    App\GraphQL\Resolver\SearchResolver:
        arguments:
            $faqFinder: '@fos_elastica.finder.app_faq'
        tags:
            - { name: overblog_graphql.resolver, alias: 'search_faq' }
    TelegramBot\Api\BotApi:
        arguments:
            $token: '%env(TELEGRAM_BOT_API_TOKEN)%'
    App\EventListener\ContactFormListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, entity: App\Entity\ContactForm }
    App\Services\Notification\Providers\EmailProvider:
        public: false
        arguments:
            $template: '/emailConfirm/confirm.html.twig'
            $isActive: '%env(bool:EMAIL_SERVICE_IS_ACTIVE)%'
            $emailFrom: '%env(EMAIL_FROM)%'