overblog_graphql_endpoint:
  resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"

overblog_graphql_single_endpoint:
  resource: "@OverblogGraphQLBundle/Resources/config/routing/single.yaml"
  prefix: /graphql


