framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'
        
        routing:
            'App\Message\TelegramNotificationMessage': async
            'App\Message\ContactFormNotificationMessage': async