security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users

            form_login:
                check_path: security_login
                login_path: security_login
                enable_csrf: true
                default_target_path: admin
                password_parameter: password
                username_parameter: username

            custom_authenticators:
                - App\Security\AppAuthenticator

            logout:
                path: security_logout
                target: /login
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                csrf_token_generator: security.csrf.token_manager

            entry_point: 'form_login'

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        firewalls:
            main:
                http_basic: ~